#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
# This role installs rackscheds.

- import_tasks: docker_login.yml

- name: get racksched name and index
  set_fact:
    racksched_name: "{{ name_prefix ~ ((racksched_index_base | int) + host_group.index(inventory_hostname)) }}"
    racksched_index: "{{ (racksched_index_base | int) + host_group.index(inventory_hostname) }}"

- name: "pull racksched image with tag {{docker.image.tag}}"
  shell: "docker pull {{docker_registry}}{{ docker.image.prefix }}/racksched:{{docker.image.tag}}"
  when: docker_registry != ""
  register: result
  until: (result.rc == 0)
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: "determine docker root dir on docker-machine"
  uri:  url="http://{{ ansible_host }}:{{ docker.port }}/info" return_content=yes
  register: dockerInfo_output
  when: environmentInformation.type == 'docker-machine'

- set_fact:
    dockerInfo: "{{ dockerInfo_output['json'] }}"
  when: environmentInformation.type == "docker-machine"

- name: "determine docker root dir"
  shell: echo -e "GET http:/v1.24/info HTTP/1.0\r\n" | nc -U /var/run/docker.sock | grep "{"
  args:
    executable: /bin/bash
  register: dockerInfo_output
  when: environmentInformation.type != "docker-machine"

- set_fact:
    dockerInfo: "{{ dockerInfo_output.stdout|from_json }}"
  when: environmentInformation.type != "docker-machine"

- name: ensure racksched log directory is created with permissions
  file:
    path: "{{ whisk_logs_dir }}/{{ racksched_name }}"
    state: directory
    mode: 0777
  become: "{{ logs.dir.become }}"

- name: ensure racksched config directory is created with permissions
  file:
    path: "{{ racksched.confdir }}/{{ racksched_name }}"
    state: directory
    mode: 0777
  become: "{{ racksched.dir.become }}"

- name: "copy kafka truststore/keystore"
  when: kafka.protocol == 'SSL'
  copy:
    src: "{{ openwhisk_home }}/ansible/roles/kafka/files/{{ kafka.ssl.keystore.name }}"
    dest: "{{ racksched.confdir }}/{{ racksched_name }}"

- name: copy keystore, key and cert
  when: racksched.protocol == "https"
  copy:
    src: "{{ rksch_item }}"
    mode: 0666
    dest: "{{ racksched.confdir }}/{{ racksched_name }}"
  become: "{{ racksched.dir.become }}"
  with_items:
  - "{{ openwhisk_home }}/ansible/roles/racksched/files/{{ racksched.ssl.keystore.name }}"
  - "{{ openwhisk_home }}/ansible/roles/racksched/files/{{ racksched.ssl.key }}"
  - "{{ openwhisk_home }}/ansible/roles/racksched/files/{{ racksched.ssl.cert }}"
  loop_control:
    loop_var: rksch_item

- name: check, that required databases exist
  include_tasks: "{{ openwhisk_home }}/ansible/tasks/db/checkDb.yml"
  vars:
    dbName: "{{ rksch_item }}"
    dbUser: "{{ db.credentials.racksched.user }}"
    dbPass: "{{ db.credentials.racksched.pass }}"
  with_items:
  - "{{ db.whisk.actions }}"
  - "{{ db.whisk.activations }}"
  loop_control:
    loop_var: rksch_item

- name: get running racksched information
  uri: url="http://{{ ansible_host }}:{{ docker.port }}/containers/json?filters={{ '{"name":[ "racksched" ],"ancestor":[ "racksched" ]}' | urlencode }}" return_content=yes
  register: rackschedInfo_output
  when: environmentInformation.type == "docker-machine"

- set_fact:
    rackschedInfo: "{{ rackschedInfo_output['json'] }}"
  when: environmentInformation.type == "docker-machine"

- name: "get racksched info"
  shell: |
    INFO=`echo -e "GET http:/v1.24/containers/json?filters={{ '{"name":[ "racksched" ],"ancestor":[ "racksched" ]}' | urlencode }} HTTP/1.0\r\n" | nc -U /var/run/docker.sock | grep "{"`
    if [ -z "$INFO" ]; then
      echo []
    else
      echo $INFO
    fi
  args:
    executable: /bin/bash
  register: rackschedInfo_output
  when: environmentInformation.type != "docker-machine"

- set_fact:
    rackschedInfo: "{{ rackschedInfo_output.stdout|from_json }}"
  when: environmentInformation.type != "docker-machine"

- name: determine if more than one racksched is running
  fail:
    msg: "more than one racksched is running"
  when: not racksched.allowMultipleInstances and rackschedInfo|length > 1

- name: determine if index of racksched is same with index of inventory host
  fail:
    msg: "racksched index is invalid. expected: /racksched{{ groups['rackscheds'].index(inventory_hostname) }} found: {{ rksch_item.Names[0] }}"
  with_items: "{{ rackschedInfo }}"
  when: not racksched.allowMultipleInstances and rksch_item.Names[0] != "/{{ racksched_name }}"
  loop_control:
    loop_var: rksch_item

- name: copy jmxremote password file
  when: jmx.enabled
  template:
    src: "jmxremote.password.j2"
    dest: "{{ racksched.confdir  }}/{{ racksched_name }}/jmxremote.password"
    mode: 0777

- name: copy jmxremote access file
  when: jmx.enabled
  template:
    src: "jmxremote.access.j2"
    dest: "{{ racksched.confdir  }}/{{ racksched_name }}/jmxremote.access"
    mode: 0777

- name: add additional jvm params if jmxremote is enabled
  when: jmx.enabled
  set_fact:
    racksched_args: "{{ racksched.arguments }} {{ racksched.jmxremote.jvmArgs }}"

- name: prepare racksched ports
  set_fact:
    racksched_ports_to_expose: ["{{ racksched.basePort + (racksched_index | int) }}:8080"]

- name: expose additional ports if jmxremote is enabled
  when: jmx.enabled
  set_fact:
    racksched_ports_to_expose: "{{ racksched_ports_to_expose }} + [ \"{{ jmx.basePortRackSched + (racksched_index | int) }}:{{ jmx.basePortRackSched + (racksched_index | int) }}\" ] + [ \"{{ jmx.rmiBasePortRackSched + (racksched_index | int) }}:{{ jmx.rmiBasePortRackSched + (racksched_index | int) }}\" ]"


- name: Load config from template
  set_fact:
    openwhisk_config: "{{ lookup('template', 'config.j2') | b64encode }}"

- name: populate environment variables for racksched
  set_fact:
    env:
      "JAVA_OPTS": "-Xmx{{ racksched.heap }} -XX:+CrashOnOutOfMemoryError -XX:+UseGCOverheadLimit -XX:ErrorFile=/logs/java_error.log"
      "RACKSCHED_OPTS": "{{ racksched_args | default(racksched.arguments) }}"
      "JMX_REMOTE": "{{ jmx.enabled }}"
      "OPENWHISK_ENCODED_CONFIG": "{{ openwhisk_config }}"
      "PORT": "8080"
      "TZ": "{{ docker.timezone }}"
      "CONFIG_whisk_info_date": "{{ whisk.version.date }}"
      "CONFIG_whisk_info_buildNo": "{{ docker.image.tag }}"
      "KAFKA_HOSTS": "{{ kafka_connect_string }}"
      "CONFIG_whisk_kafka_replicationFactor": "{{ kafka.replicationFactor | default() }}"
      "CONFIG_whisk_kafka_topics_racksched_retentionBytes": "{{ kafka_topics_racksched_retentionBytes | default() }}"
      "CONFIG_whisk_kafka_topics_racksched_retentionMs": "{{ kafka_topics_racksched_retentionMS | default() }}"
      "CONFIG_whisk_kakfa_topics_racksched_segmentBytes": "{{ kafka_topics_racksched_segmentBytes | default() }}"
      "CONFIG_whisk_kafka_common_securityProtocol": "{{ kafka.protocol }}"
      "CONFIG_whisk_kafka_common_sslTruststoreLocation": "/conf/{{ kafka.ssl.keystore.name }}"
      "CONFIG_whisk_kafka_common_sslTruststorePassword": "{{ kafka.ssl.keystore.password }}"
      "CONFIG_whisk_kafka_common_sslKeystoreLocation": "/conf/{{ kafka.ssl.keystore.name }}"
      "CONFIG_whisk_kafka_common_sslKeystorePassword": "{{ kafka.ssl.keystore.password }}"
      "CONFIG_whisk_userEvents_enabled": "{{ user_events | default(false) | lower }}"
      "ZOOKEEPER_HOSTS": "{{ zookeeper_connect_string }}"
      "CONFIG_whisk_couchdb_protocol": "{{ db.protocol }}"
      "CONFIG_whisk_couchdb_host": "{{ db.host }}"
      "CONFIG_whisk_couchdb_port": "{{ db.port }}"
      "CONFIG_whisk_couchdb_username": "{{ db.credentials.racksched.user }}"
      "CONFIG_whisk_couchdb_password": "{{ db.credentials.racksched.pass }}"
      "CONFIG_whisk_couchdb_provider": "{{ db.provider }}"
      "CONFIG_whisk_couchdb_databases_WhiskAuth": "{{ db.whisk.auth }}"
      "CONFIG_whisk_couchdb_databases_WhiskEntity": "{{ db.whisk.actions }}"
      "CONFIG_whisk_couchdb_databases_WhiskActivation": "{{ db.whisk.activations }}"
      "DB_WHISK_ACTIONS": "{{ db.whisk.actions }}"
      "DB_WHISK_ACTIVATIONS": "{{ db.whisk.activations }}"
      "DB_WHISK_AUTHS": "{{ db.whisk.auth }}"
      "CONFIG_whisk_db_subjectsDdoc": "{{ db_whisk_subjects_ddoc | default() }}"
      "CONFIG_whisk_db_actionsDdoc": "{{ db_whisk_actions_ddoc | default() }}"
      "CONFIG_whisk_db_activationsDdoc": "{{ db_whisk_activations_ddoc | default() }}"
      "CONFIG_whisk_db_activationsFilterDdoc": "{{ db_whisk_activations_filter_ddoc | default() }}"
      "WHISK_API_HOST_PROTO": "{{ whisk_api_host_proto | default('https') }}"
      "WHISK_API_HOST_PORT": "{{ whisk_api_host_port | default('443') }}"
      "WHISK_API_HOST_NAME": "{{ whisk_api_host_name | default(groups['edge'] | first) }}"
      "RUNTIMES_MANIFEST": "{{ runtimesManifest | to_json }}"
      "CONFIG_whisk_runtimes_bypassPullForLocalImages": "{{ runtimes_bypass_pull_for_local_images | default() | lower }}"
      "CONFIG_whisk_runtimes_localImagePrefix": "{{ runtimes_local_image_prefix | default() }}"
      "racksched_CONTAINER_POLICY": "{{ racksched_container_policy_name | default()}}"
      "CONFIG_whisk_containerPool_userMemory": "{{ hostvars[groups['rackscheds'][racksched_index | int]].user_memory | default(racksched.userMemory) }}"
      "CONFIG_whisk_docker_client_parallelRuns": "{{ racksched_parallel_runs | default() }}"
      "WHISK_LOGS_DIR": "{{ whisk_logs_dir }}"
      "METRICS_KAMON": "{{ metrics.kamon.enabled | default(false) | lower }}"
      "METRICS_KAMON_TAGS": "{{ metrics.kamon.tags | default() | lower }}"
      "METRICS_LOG": "{{ metrics.log.enabled | default(false) | lower }}"
      "CONFIG_kamon_statsd_hostname": "{{ metrics.kamon.host }}"
      "CONFIG_kamon_statsd_port": "{{ metrics.kamon.port }}"
      "CONFIG_whisk_spi_LogStoreProvider": "{{ userLogs.spi }}"
      "CONFIG_logback_log_level": "{{ racksched.loglevel }}"
      "LIMITS_ACTIONS_INVOKES_PERMINUTE": "{{ limits.invocationsPerMinute }}"
      "LIMITS_ACTIONS_INVOKES_CONCURRENT": "{{ limits.concurrentInvocations }}"
      "LIMITS_TRIGGERS_FIRES_PERMINUTE": "{{ limits.firesPerMinute }}"
      "LIMITS_ACTIONS_SEQUENCE_MAXLENGTH": "{{ limits.sequenceMaxLength }}"
      "CONFIG_whisk_memory_min": "{{ limit_action_memory_min | default() }}"
      "CONFIG_whisk_memory_max": "{{ limit_action_memory_max | default() }}"
      "CONFIG_whisk_memory_std": "{{ limit_action_memory_std | default() }}"
      "CONFIG_whisk_timeLimit_min": "{{ limit_action_time_min | default() }}"
      "CONFIG_whisk_timeLimit_max": "{{ limit_action_time_max | default() }}"
      "CONFIG_whisk_timeLimit_std": "{{ limit_action_time_std | default() }}"
      "CONFIG_whisk_concurrencyLimit_min": "{{ limit_action_concurrency_min | default() }}"
      "CONFIG_whisk_concurrencyLimit_max": "{{ limit_action_concurrency_max | default() }}"
      "CONFIG_whisk_concurrencyLimit_std": "{{ limit_action_concurrency_std | default() }}"
      "CONFIG_whisk_activation_payload_max": "{{ limit_activation_payload | default() }}"
      "CONFIG_whisk_transactions_header": "{{ transactions.header }}"
      "CONFIG_whisk_containerPool_akkaClient": "{{ container_pool_akka_client | default('false') | lower }}"
      "CONFIG_whisk_racksched_protocol": "{{ racksched.protocol }}"
      "CONFIG_whisk_racksched_https_keystorePath": "/conf/{{ racksched.ssl.keystore.name }}"
      "CONFIG_whisk_racksched_https_keystorePassword": "{{ racksched.ssl.keystore.password }}"
      "CONFIG_whisk_racksched_https_keystoreFlavor": "{{ racksched.ssl.storeFlavor }}"
      "CONFIG_whisk_racksched_https_clientAuth": "{{ racksched.ssl.clientAuth }}"
      "CONFIG_whisk_containerPool_prewarmExpirationCheckInterval": "{{ container_pool_prewarm_expirationCheckInterval | default('1 minute') }}"
      "CONFIG_whisk_rackloadbalancer_timeoutFactor":
        "{{ racksched.timeoutFactor }}"
      "CONFIG_whisk_rackloadbalancer_timeoutAddon":
        "{{ racksched.timeoutAddon }}"
      "CONFIG_whisk_spi_RackLoadBalancerProvider":
        "{{ racksched.rackloadbalancer.spi }}"

- name: merge extra env variables
  set_fact:
    env: "{{ env | combine(racksched.extraEnv) }}"

- name: setup elasticsearch activation store env
  set_fact:
    elastic_env:
      "CONFIG_whisk_activationStore_elasticsearch_protocol": "{{ db.elasticsearch.protocol}}"
      "CONFIG_whisk_activationStore_elasticsearch_hosts": "{{ elasticsearch_connect_string }}"
      "CONFIG_whisk_activationStore_elasticsearch_indexPattern": "{{ db.elasticsearch.index_pattern }}"
      "CONFIG_whisk_activationStore_elasticsearch_username": "{{ db.elasticsearch.auth.admin.username }}"
      "CONFIG_whisk_activationStore_elasticsearch_password": "{{ db.elasticsearch.auth.admin.password }}"
      "CONFIG_whisk_spi_ActivationStoreProvider": "org.apache.openwhisk.core.database.elasticsearch.ElasticSearchActivationStoreProvider"
  when: db.activation_store.backend == "ElasticSearch"

- name: merge elasticsearch activation store env
  set_fact:
    env: "{{ env | combine(elastic_env) }}"
  when: db.activation_store.backend == "ElasticSearch"

- name: include plugins
  include_tasks: "{{ rksch_item }}.yml"
  with_items: "{{ racksched_plugins | default([]) }}"
  loop_control:
    loop_var: rksch_item

- name: set racksched volumes
  set_fact:
    racksched_volumes:
    - "{{ whisk_logs_dir }}/{{ racksched_name }}:/logs"
    - "{{ racksched.confdir }}/{{ racksched_name }}:/conf"

###
# The root runc directory varies based on the version of docker and runc.
# When docker>=18.06 uses docker-runc the directory is /run/docker/runtime-runc/moby.
# While docker-runc itself uses /run/runc for a root user or /run/user/<uid>/runc for a non-root user.
# Currently, the racksched is running as a root user so the below configuration works as expected.
# But when the racksched needs to run as a non-root user or the version docker needs to be changed,
# the following configuration should be properly updated as well.
#
# Alternatively, we can disable the runc with racksched.userRunc = false.
#

- name: check if coverage collection is enabled
  set_fact:
    coverage_enabled: false
  when: coverage_enabled is undefined

- name: ensure racksched coverage directory is created with permissions
  file:
    path: "{{ coverage_logs_dir }}/racksched/{{ rksch_item }}"
    state: directory
    mode: 0777
  with_items:
    - racksched
    - common
  become: "{{ logs.dir.become }}"
  when: coverage_enabled
  loop_control:
    loop_var: rksch_item

- name: extend racksched volume for coverage
  set_fact:
    racksched_volumes: "{{ racksched_volumes|default('') }},{{ coverage_logs_dir }}/racksched:/coverage"
  when: coverage_enabled

- name: start racksched
  docker_container:
    userns_mode: "host"
    pid_mode: "host"
    privileged: "yes"
    name: "{{ racksched_name }}"
    hostname: "{{ racksched_name }}"
    restart_policy: "{{ docker.restart.policy }}"
    image: "{{ docker_registry }}{{ docker.image.prefix }}/racksched:{{ 'cov' if (coverage_enabled) else docker.image.tag }}"
    state: started
    recreate: true
    env: "{{ env }}"
    volumes: "{{ racksched_volumes }}"
    ports: "{{ racksched_ports_to_expose }}"
    command: /bin/sh -c "exec /init.sh --id {{ racksched_index }} --uniqueName {{ racksched_index }}  >> /logs/{{ racksched_name }}_logs.log 2>&1"
  when: not lean

- name: wait until Racksched is up and running
  uri:
    url: "{{ racksched.protocol }}://{{ ansible_host }}:{{ racksched.basePort + (racksched_index | int) }}/ping"
    validate_certs: "no"
    client_key: "{{ racksched.confdir }}/{{ racksched_name }}/{{ racksched.ssl.key }}"
    client_cert: "{{ racksched.confdir }}/{{ racksched_name }}/{{ racksched.ssl.cert }}"
  register: result
  until: result.status == 200
  retries: 12
  delay: 5
  when: not lean
