- hosts: all
  vars:
    gh_branch: main
    repo_dir: /home/wuklab/projects/disagg-serverless
  tasks:
  - name: fetch latest code
    shell: 'cd {{ repo_dir }} && git fetch origin && git checkout -B {{gh_branch}} origin/{{gh_branch}}  && git pull origin'
  - name: compile and build runtimes
    shell: cd {{repo_dir }}/runtime && make all
  - name: compile and build openwhisk containers
    shell: 'cd {{ repo_dir }}/openwhisk && ./gradlew distDocker -x test'
