schemas = {
    "call_center": [
        [
            "cc_call_center_sk",
            "INT"
        ],
        [
            "cc_call_center_id",
            "CHAR"
        ],
        [
            "cc_rec_start_date",
            "DATE"
        ],
        [
            "cc_rec_end_date",
            "DATE"
        ],
        [
            "cc_closed_date_sk",
            "INT"
        ],
        [
            "cc_open_date_sk",
            "INT"
        ],
        [
            "cc_name",
            "VARCHAR"
        ],
        [
            "cc_class",
            "VARCHAR"
        ],
        [
            "cc_employees",
            "INT"
        ],
        [
            "cc_sq_ft",
            "INT"
        ],
        [
            "cc_hours",
            "CHAR"
        ],
        [
            "cc_manager",
            "VARCHAR"
        ],
        [
            "cc_mkt_id",
            "INT"
        ],
        [
            "cc_mkt_class",
            "CHAR"
        ],
        [
            "cc_mkt_desc",
            "VARCHAR"
        ],
        [
            "cc_market_manager",
            "VARCHAR"
        ],
        [
            "cc_division",
            "INT"
        ],
        [
            "cc_division_name",
            "VARCHAR"
        ],
        [
            "cc_company",
            "INT"
        ],
        [
            "cc_company_name",
            "CHAR"
        ],
        [
            "cc_street_number",
            "CHAR"
        ],
        [
            "cc_street_name",
            "VARCHAR"
        ],
        [
            "cc_street_type",
            "CHAR"
        ],
        [
            "cc_suite_number",
            "CHAR"
        ],
        [
            "cc_city",
            "VARCHAR"
        ],
        [
            "cc_county",
            "VARCHAR"
        ],
        [
            "cc_state",
            "CHAR"
        ],
        [
            "cc_zip",
            "CHAR"
        ],
        [
            "cc_country",
            "VARCHAR"
        ],
        [
            "cc_gmt_offset",
            "DECIMAL"
        ],
        [
            "cc_tax_percentage",
            "DECIMAL"
        ]
    ],
    "catalog_page": [
        [
            "cp_catalog_page_sk",
            "INT"
        ],
        [
            "cp_catalog_page_id",
            "CHAR"
        ],
        [
            "cp_start_date_sk",
            "INT"
        ],
        [
            "cp_end_date_sk",
            "INT"
        ],
        [
            "cp_department",
            "VARCHAR"
        ],
        [
            "cp_catalog_number",
            "INT"
        ],
        [
            "cp_catalog_page_number",
            "INT"
        ],
        [
            "cp_description",
            "VARCHAR"
        ],
        [
            "cp_type",
            "VARCHAR"
        ]
    ],
    "catalog_returns": [
        [
            "cr_returned_date_sk",
            "INT"
        ],
        [
            "cr_returned_time_sk",
            "INT"
        ],
        [
            "cr_item_sk",
            "INT"
        ],
        [
            "cr_refunded_customer_sk",
            "INT"
        ],
        [
            "cr_refunded_cdemo_sk",
            "INT"
        ],
        [
            "cr_refunded_hdemo_sk",
            "INT"
        ],
        [
            "cr_refunded_addr_sk",
            "INT"
        ],
        [
            "cr_returning_customer_sk",
            "INT"
        ],
        [
            "cr_returning_cdemo_sk",
            "INT"
        ],
        [
            "cr_returning_hdemo_sk",
            "INT"
        ],
        [
            "cr_returning_addr_sk",
            "INT"
        ],
        [
            "cr_call_center_sk",
            "INT"
        ],
        [
            "cr_catalog_page_sk",
            "INT"
        ],
        [
            "cr_ship_mode_sk",
            "INT"
        ],
        [
            "cr_warehouse_sk",
            "INT"
        ],
        [
            "cr_reason_sk",
            "INT"
        ],
        [
            "cr_order_number",
            "INT"
        ],
        [
            "cr_return_quantity",
            "INT"
        ],
        [
            "cr_return_amount",
            "DECIMAL"
        ],
        [
            "cr_return_tax",
            "DECIMAL"
        ],
        [
            "cr_return_amt_inc_tax",
            "DECIMAL"
        ],
        [
            "cr_fee",
            "DECIMAL"
        ],
        [
            "cr_return_ship_cost",
            "DECIMAL"
        ],
        [
            "cr_refunded_cash",
            "DECIMAL"
        ],
        [
            "cr_reversed_charge",
            "DECIMAL"
        ],
        [
            "cr_store_credit",
            "DECIMAL"
        ],
        [
            "cr_net_loss",
            "DECIMAL"
        ]
    ],
    "catalog_sales": [
        [
            "cs_sold_date_sk",
            "INT"
        ],
        [
            "cs_sold_time_sk",
            "INT"
        ],
        [
            "cs_ship_date_sk",
            "INT"
        ],
        [
            "cs_bill_customer_sk",
            "INT"
        ],
        [
            "cs_bill_cdemo_sk",
            "INT"
        ],
        [
            "cs_bill_hdemo_sk",
            "INT"
        ],
        [
            "cs_bill_addr_sk",
            "INT"
        ],
        [
            "cs_ship_customer_sk",
            "INT"
        ],
        [
            "cs_ship_cdemo_sk",
            "INT"
        ],
        [
            "cs_ship_hdemo_sk",
            "INT"
        ],
        [
            "cs_ship_addr_sk",
            "INT"
        ],
        [
            "cs_call_center_sk",
            "INT"
        ],
        [
            "cs_catalog_page_sk",
            "INT"
        ],
        [
            "cs_ship_mode_sk",
            "INT"
        ],
        [
            "cs_warehouse_sk",
            "INT"
        ],
        [
            "cs_item_sk",
            "INT"
        ],
        [
            "cs_promo_sk",
            "INT"
        ],
        [
            "cs_order_number",
            "INT"
        ],
        [
            "cs_quantity",
            "INT"
        ],
        [
            "cs_wholesale_cost",
            "DECIMAL"
        ],
        [
            "cs_list_price",
            "DECIMAL"
        ],
        [
            "cs_sales_price",
            "DECIMAL"
        ],
        [
            "cs_ext_discount_amt",
            "DECIMAL"
        ],
        [
            "cs_ext_sales_price",
            "DECIMAL"
        ],
        [
            "cs_ext_wholesale_cost",
            "DECIMAL"
        ],
        [
            "cs_ext_list_price",
            "DECIMAL"
        ],
        [
            "cs_ext_tax",
            "DECIMAL"
        ],
        [
            "cs_coupon_amt",
            "DECIMAL"
        ],
        [
            "cs_ext_ship_cost",
            "DECIMAL"
        ],
        [
            "cs_net_paid",
            "DECIMAL"
        ],
        [
            "cs_net_paid_inc_tax",
            "DECIMAL"
        ],
        [
            "cs_net_paid_inc_ship",
            "DECIMAL"
        ],
        [
            "cs_net_paid_inc_ship_tax",
            "DECIMAL"
        ],
        [
            "cs_net_profit",
            "DECIMAL"
        ]
    ],
    "customer": [
        [
            "c_customer_sk",
            "INT"
        ],
        [
            "c_customer_id",
            "CHAR"
        ],
        [
            "c_current_cdemo_sk",
            "INT"
        ],
        [
            "c_current_hdemo_sk",
            "INT"
        ],
        [
            "c_current_addr_sk",
            "INT"
        ],
        [
            "c_first_shipto_date_sk",
            "INT"
        ],
        [
            "c_first_sales_date_sk",
            "INT"
        ],
        [
            "c_salutation",
            "CHAR"
        ],
        [
            "c_first_name",
            "CHAR"
        ],
        [
            "c_last_name",
            "CHAR"
        ],
        [
            "c_preferred_cust_flag",
            "CHAR"
        ],
        [
            "c_birth_day",
            "INT"
        ],
        [
            "c_birth_month",
            "INT"
        ],
        [
            "c_birth_year",
            "INT"
        ],
        [
            "c_birth_country",
            "VARCHAR"
        ],
        [
            "c_login",
            "CHAR"
        ],
        [
            "c_email_address",
            "CHAR"
        ],
        [
            "c_last_review_date",
            "CHAR"
        ]
    ],
    "customer_address": [
        [
            "ca_address_sk",
            "INT"
        ],
        [
            "ca_address_id",
            "CHAR"
        ],
        [
            "ca_street_number",
            "CHAR"
        ],
        [
            "ca_street_name",
            "VARCHAR"
        ],
        [
            "ca_street_type",
            "CHAR"
        ],
        [
            "ca_suite_number",
            "CHAR"
        ],
        [
            "ca_city",
            "VARCHAR"
        ],
        [
            "ca_county",
            "VARCHAR"
        ],
        [
            "ca_state",
            "CHAR"
        ],
        [
            "ca_zip",
            "CHAR"
        ],
        [
            "ca_country",
            "VARCHAR"
        ],
        [
            "ca_gmt_offset",
            "DECIMAL"
        ],
        [
            "ca_location_type",
            "CHAR"
        ]
    ],
    "customer_demographics": [
        [
            "cd_demo_sk",
            "INT"
        ],
        [
            "cd_gender",
            "CHAR"
        ],
        [
            "cd_marital_status",
            "CHAR"
        ],
        [
            "cd_education_status",
            "CHAR"
        ],
        [
            "cd_purchase_estimate",
            "INT"
        ],
        [
            "cd_credit_rating",
            "CHAR"
        ],
        [
            "cd_dep_count",
            "INT"
        ],
        [
            "cd_dep_employed_count",
            "INT"
        ],
        [
            "cd_dep_college_count",
            "INT"
        ]
    ],
    "date_dim": [
        [
            "d_date_sk",
            "INT"
        ],
        [
            "d_date_id",
            "CHAR"
        ],
        [
            "d_date",
            "DATE"
        ],
        [
            "d_month_seq",
            "INT"
        ],
        [
            "d_week_seq",
            "INT"
        ],
        [
            "d_quarter_seq",
            "INT"
        ],
        [
            "d_year",
            "INT"
        ],
        [
            "d_dow",
            "INT"
        ],
        [
            "d_moy",
            "INT"
        ],
        [
            "d_dom",
            "INT"
        ],
        [
            "d_qoy",
            "INT"
        ],
        [
            "d_fy_year",
            "INT"
        ],
        [
            "d_fy_quarter_seq",
            "INT"
        ],
        [
            "d_fy_week_seq",
            "INT"
        ],
        [
            "d_day_name",
            "CHAR"
        ],
        [
            "d_quarter_name",
            "CHAR"
        ],
        [
            "d_holiday",
            "CHAR"
        ],
        [
            "d_weekend",
            "CHAR"
        ],
        [
            "d_following_holiday",
            "CHAR"
        ],
        [
            "d_first_dom",
            "INT"
        ],
        [
            "d_last_dom",
            "INT"
        ],
        [
            "d_same_day_ly",
            "INT"
        ],
        [
            "d_same_day_lq",
            "INT"
        ],
        [
            "d_current_day",
            "CHAR"
        ],
        [
            "d_current_week",
            "CHAR"
        ],
        [
            "d_current_month",
            "CHAR"
        ],
        [
            "d_current_quarter",
            "CHAR"
        ],
        [
            "d_current_year",
            "CHAR"
        ]
    ],
    "household_demographics": [
        [
            "hd_demo_sk",
            "INT"
        ],
        [
            "hd_income_band_sk",
            "INT"
        ],
        [
            "hd_buy_potential",
            "CHAR"
        ],
        [
            "hd_dep_count",
            "INT"
        ],
        [
            "hd_vehicle_count",
            "INT"
        ]
    ],
    "income_band": [
        [
            "ib_income_band_sk",
            "INT"
        ],
        [
            "ib_lower_bound",
            "INT"
        ],
        [
            "ib_upper_bound",
            "INT"
        ]
    ],
    "inventory": [
        [
            "inv_date_sk",
            "INT"
        ],
        [
            "inv_item_sk",
            "INT"
        ],
        [
            "inv_warehouse_sk",
            "INT"
        ],
        [
            "inv_quantity_on_hand",
            "INT"
        ]
    ],
    "item": [
        [
            "i_item_sk",
            "INT"
        ],
        [
            "i_item_id",
            "CHAR"
        ],
        [
            "i_rec_start_date",
            "DATE"
        ],
        [
            "i_rec_end_date",
            "DATE"
        ],
        [
            "i_item_desc",
            "VARCHAR"
        ],
        [
            "i_current_price",
            "DECIMAL"
        ],
        [
            "i_wholesale_cost",
            "DECIMAL"
        ],
        [
            "i_brand_id",
            "INT"
        ],
        [
            "i_brand",
            "CHAR"
        ],
        [
            "i_class_id",
            "INT"
        ],
        [
            "i_class",
            "CHAR"
        ],
        [
            "i_category_id",
            "INT"
        ],
        [
            "i_category",
            "CHAR"
        ],
        [
            "i_manufact_id",
            "INT"
        ],
        [
            "i_manufact",
            "CHAR"
        ],
        [
            "i_size",
            "CHAR"
        ],
        [
            "i_formulation",
            "CHAR"
        ],
        [
            "i_color",
            "CHAR"
        ],
        [
            "i_units",
            "CHAR"
        ],
        [
            "i_container",
            "CHAR"
        ],
        [
            "i_manager_id",
            "INT"
        ],
        [
            "i_product_name",
            "CHAR"
        ]
    ],
    "promotion": [
        [
            "p_promo_sk",
            "INT"
        ],
        [
            "p_promo_id",
            "CHAR"
        ],
        [
            "p_start_date_sk",
            "INT"
        ],
        [
            "p_end_date_sk",
            "INT"
        ],
        [
            "p_item_sk",
            "INT"
        ],
        [
            "p_cost",
            "DECIMAL"
        ],
        [
            "p_response_target",
            "INT"
        ],
        [
            "p_promo_name",
            "CHAR"
        ],
        [
            "p_channel_dmail",
            "CHAR"
        ],
        [
            "p_channel_email",
            "CHAR"
        ],
        [
            "p_channel_catalog",
            "CHAR"
        ],
        [
            "p_channel_tv",
            "CHAR"
        ],
        [
            "p_channel_radio",
            "CHAR"
        ],
        [
            "p_channel_press",
            "CHAR"
        ],
        [
            "p_channel_event",
            "CHAR"
        ],
        [
            "p_channel_demo",
            "CHAR"
        ],
        [
            "p_channel_details",
            "VARCHAR"
        ],
        [
            "p_purpose",
            "CHAR"
        ],
        [
            "p_discount_active",
            "CHAR"
        ]
    ],
    "reason": [
        [
            "r_reason_sk",
            "INT"
        ],
        [
            "r_reason_id",
            "CHAR"
        ],
        [
            "r_reason_desc",
            "CHAR"
        ]
    ],
    "ship_mode": [
        [
            "sm_ship_mode_sk",
            "INT"
        ],
        [
            "sm_ship_mode_id",
            "CHAR"
        ],
        [
            "sm_type",
            "CHAR"
        ],
        [
            "sm_code",
            "CHAR"
        ],
        [
            "sm_carrier",
            "CHAR"
        ],
        [
            "sm_contract",
            "CHAR"
        ]
    ],
    "store": [
        [
            "s_store_sk",
            "INT"
        ],
        [
            "s_store_id",
            "CHAR"
        ],
        [
            "s_rec_start_date",
            "DATE"
        ],
        [
            "s_rec_end_date",
            "DATE"
        ],
        [
            "s_closed_date_sk",
            "INT"
        ],
        [
            "s_store_name",
            "VARCHAR"
        ],
        [
            "s_number_employees",
            "INT"
        ],
        [
            "s_floor_space",
            "INT"
        ],
        [
            "s_hours",
            "CHAR"
        ],
        [
            "s_manager",
            "VARCHAR"
        ],
        [
            "s_market_id",
            "INT"
        ],
        [
            "s_geography_class",
            "VARCHAR"
        ],
        [
            "s_market_desc",
            "VARCHAR"
        ],
        [
            "s_market_manager",
            "VARCHAR"
        ],
        [
            "s_division_id",
            "INT"
        ],
        [
            "s_division_name",
            "VARCHAR"
        ],
        [
            "s_company_id",
            "INT"
        ],
        [
            "s_company_name",
            "VARCHAR"
        ],
        [
            "s_street_number",
            "VARCHAR"
        ],
        [
            "s_street_name",
            "VARCHAR"
        ],
        [
            "s_street_type",
            "CHAR"
        ],
        [
            "s_suite_number",
            "CHAR"
        ],
        [
            "s_city",
            "VARCHAR"
        ],
        [
            "s_county",
            "VARCHAR"
        ],
        [
            "s_state",
            "CHAR"
        ],
        [
            "s_zip",
            "CHAR"
        ],
        [
            "s_country",
            "VARCHAR"
        ],
        [
            "s_gmt_offset",
            "DECIMAL"
        ],
        [
            "s_tax_precentage",
            "DECIMAL"
        ]
    ],
    "store_returns": [
        [
            "sr_returned_date_sk",
            "INT"
        ],
        [
            "sr_return_time_sk",
            "INT"
        ],
        [
            "sr_item_sk",
            "INT"
        ],
        [
            "sr_customer_sk",
            "INT"
        ],
        [
            "sr_cdemo_sk",
            "INT"
        ],
        [
            "sr_hdemo_sk",
            "INT"
        ],
        [
            "sr_addr_sk",
            "INT"
        ],
        [
            "sr_store_sk",
            "INT"
        ],
        [
            "sr_reason_sk",
            "INT"
        ],
        [
            "sr_ticket_number",
            "INT"
        ],
        [
            "sr_return_quantity",
            "INT"
        ],
        [
            "sr_return_amt",
            "DECIMAL"
        ],
        [
            "sr_return_tax",
            "DECIMAL"
        ],
        [
            "sr_return_amt_inc_tax",
            "DECIMAL"
        ],
        [
            "sr_fee",
            "DECIMAL"
        ],
        [
            "sr_return_ship_cost",
            "DECIMAL"
        ],
        [
            "sr_refunded_cash",
            "DECIMAL"
        ],
        [
            "sr_reversed_charge",
            "DECIMAL"
        ],
        [
            "sr_store_credit",
            "DECIMAL"
        ],
        [
            "sr_net_loss",
            "DECIMAL"
        ]
    ],
    "store_sales": [
        [
            "ss_sold_date_sk",
            "INT"
        ],
        [
            "ss_sold_time_sk",
            "INT"
        ],
        [
            "ss_item_sk",
            "INT"
        ],
        [
            "ss_customer_sk",
            "INT"
        ],
        [
            "ss_cdemo_sk",
            "INT"
        ],
        [
            "ss_hdemo_sk",
            "INT"
        ],
        [
            "ss_addr_sk",
            "INT"
        ],
        [
            "ss_store_sk",
            "INT"
        ],
        [
            "ss_promo_sk",
            "INT"
        ],
        [
            "ss_ticket_number",
            "INT"
        ],
        [
            "ss_quantity",
            "INT"
        ],
        [
            "ss_wholesale_cost",
            "DECIMAL"
        ],
        [
            "ss_list_price",
            "DECIMAL"
        ],
        [
            "ss_sales_price",
            "DECIMAL"
        ],
        [
            "ss_ext_discount_amt",
            "DECIMAL"
        ],
        [
            "ss_ext_sales_price",
            "DECIMAL"
        ],
        [
            "ss_ext_wholesale_cost",
            "DECIMAL"
        ],
        [
            "ss_ext_list_price",
            "DECIMAL"
        ],
        [
            "ss_ext_tax",
            "DECIMAL"
        ],
        [
            "ss_coupon_amt",
            "DECIMAL"
        ],
        [
            "ss_net_paid",
            "DECIMAL"
        ],
        [
            "ss_net_paid_inc_tax",
            "DECIMAL"
        ],
        [
            "ss_net_profit",
            "DECIMAL"
        ]
    ],
    "time_dim": [
        [
            "t_time_sk",
            "INT"
        ],
        [
            "t_time_id",
            "CHAR"
        ],
        [
            "t_time",
            "INT"
        ],
        [
            "t_hour",
            "INT"
        ],
        [
            "t_minute",
            "INT"
        ],
        [
            "t_second",
            "INT"
        ],
        [
            "t_am_pm",
            "CHAR"
        ],
        [
            "t_shift",
            "CHAR"
        ],
        [
            "t_sub_shift",
            "CHAR"
        ],
        [
            "t_meal_time",
            "CHAR"
        ]
    ],
    "warehouse": [
        [
            "w_warehouse_sk",
            "INT"
        ],
        [
            "w_warehouse_id",
            "CHAR"
        ],
        [
            "w_warehouse_name",
            "VARCHAR"
        ],
        [
            "w_warehouse_sq_ft",
            "INT"
        ],
        [
            "w_street_number",
            "CHAR"
        ],
        [
            "w_street_name",
            "VARCHAR"
        ],
        [
            "w_street_type",
            "CHAR"
        ],
        [
            "w_suite_number",
            "CHAR"
        ],
        [
            "w_city",
            "VARCHAR"
        ],
        [
            "w_county",
            "VARCHAR"
        ],
        [
            "w_state",
            "CHAR"
        ],
        [
            "w_zip",
            "CHAR"
        ],
        [
            "w_country",
            "VARCHAR"
        ],
        [
            "w_gmt_offset",
            "DECIMAL"
        ]
    ],
    "web_page": [
        [
            "wp_web_page_sk",
            "INT"
        ],
        [
            "wp_web_page_id",
            "CHAR"
        ],
        [
            "wp_rec_start_date",
            "DATE"
        ],
        [
            "wp_rec_end_date",
            "DATE"
        ],
        [
            "wp_creation_date_sk",
            "INT"
        ],
        [
            "wp_access_date_sk",
            "INT"
        ],
        [
            "wp_autogen_flag",
            "CHAR"
        ],
        [
            "wp_customer_sk",
            "INT"
        ],
        [
            "wp_url",
            "VARCHAR"
        ],
        [
            "wp_type",
            "CHAR"
        ],
        [
            "wp_char_count",
            "INT"
        ],
        [
            "wp_link_count",
            "INT"
        ],
        [
            "wp_image_count",
            "INT"
        ],
        [
            "wp_max_ad_count",
            "INT"
        ]
    ],
    "web_returns": [
        [
            "wr_returned_date_sk",
            "INT"
        ],
        [
            "wr_returned_time_sk",
            "INT"
        ],
        [
            "wr_item_sk",
            "INT"
        ],
        [
            "wr_refunded_customer_sk",
            "INT"
        ],
        [
            "wr_refunded_cdemo_sk",
            "INT"
        ],
        [
            "wr_refunded_hdemo_sk",
            "INT"
        ],
        [
            "wr_refunded_addr_sk",
            "INT"
        ],
        [
            "wr_returning_customer_sk",
            "INT"
        ],
        [
            "wr_returning_cdemo_sk",
            "INT"
        ],
        [
            "wr_returning_hdemo_sk",
            "INT"
        ],
        [
            "wr_returning_addr_sk",
            "INT"
        ],
        [
            "wr_web_page_sk",
            "INT"
        ],
        [
            "wr_reason_sk",
            "INT"
        ],
        [
            "wr_order_number",
            "INT"
        ],
        [
            "wr_return_quantity",
            "INT"
        ],
        [
            "wr_return_amt",
            "DECIMAL"
        ],
        [
            "wr_return_tax",
            "DECIMAL"
        ],
        [
            "wr_return_amt_inc_tax",
            "DECIMAL"
        ],
        [
            "wr_fee",
            "DECIMAL"
        ],
        [
            "wr_return_ship_cost",
            "DECIMAL"
        ],
        [
            "wr_refunded_cash",
            "DECIMAL"
        ],
        [
            "wr_reversed_charge",
            "DECIMAL"
        ],
        [
            "wr_account_credit",
            "DECIMAL"
        ],
        [
            "wr_net_loss",
            "DECIMAL"
        ]
    ],
    "web_sales": [
        [
            "ws_sold_date_sk",
            "INT"
        ],
        [
            "ws_sold_time_sk",
            "INT"
        ],
        [
            "ws_ship_date_sk",
            "INT"
        ],
        [
            "ws_item_sk",
            "INT"
        ],
        [
            "ws_bill_customer_sk",
            "INT"
        ],
        [
            "ws_bill_cdemo_sk",
            "INT"
        ],
        [
            "ws_bill_hdemo_sk",
            "INT"
        ],
        [
            "ws_bill_addr_sk",
            "INT"
        ],
        [
            "ws_ship_customer_sk",
            "INT"
        ],
        [
            "ws_ship_cdemo_sk",
            "INT"
        ],
        [
            "ws_ship_hdemo_sk",
            "INT"
        ],
        [
            "ws_ship_addr_sk",
            "INT"
        ],
        [
            "ws_web_page_sk",
            "INT"
        ],
        [
            "ws_web_site_sk",
            "INT"
        ],
        [
            "ws_ship_mode_sk",
            "INT"
        ],
        [
            "ws_warehouse_sk",
            "INT"
        ],
        [
            "ws_promo_sk",
            "INT"
        ],
        [
            "ws_order_number",
            "INT"
        ],
        [
            "ws_quantity",
            "INT"
        ],
        [
            "ws_wholesale_cost",
            "DECIMAL"
        ],
        [
            "ws_list_price",
            "DECIMAL"
        ],
        [
            "ws_sales_price",
            "DECIMAL"
        ],
        [
            "ws_ext_discount_amt",
            "DECIMAL"
        ],
        [
            "ws_ext_sales_price",
            "DECIMAL"
        ],
        [
            "ws_ext_wholesale_cost",
            "DECIMAL"
        ],
        [
            "ws_ext_list_price",
            "DECIMAL"
        ],
        [
            "ws_ext_tax",
            "DECIMAL"
        ],
        [
            "ws_coupon_amt",
            "DECIMAL"
        ],
        [
            "ws_ext_ship_cost",
            "DECIMAL"
        ],
        [
            "ws_net_paid",
            "DECIMAL"
        ],
        [
            "ws_net_paid_inc_tax",
            "DECIMAL"
        ],
        [
            "ws_net_paid_inc_ship",
            "DECIMAL"
        ],
        [
            "ws_net_paid_inc_ship_tax",
            "DECIMAL"
        ],
        [
            "ws_net_profit",
            "DECIMAL"
        ]
    ],
    "web_site": [
        [
            "web_site_sk",
            "INT"
        ],
        [
            "web_site_id",
            "CHAR"
        ],
        [
            "web_rec_start_date",
            "DATE"
        ],
        [
            "web_rec_end_date",
            "DATE"
        ],
        [
            "web_name",
            "VARCHAR"
        ],
        [
            "web_open_date_sk",
            "INT"
        ],
        [
            "web_close_date_sk",
            "INT"
        ],
        [
            "web_class",
            "VARCHAR"
        ],
        [
            "web_manager",
            "VARCHAR"
        ],
        [
            "web_mkt_id",
            "INT"
        ],
        [
            "web_mkt_class",
            "VARCHAR"
        ],
        [
            "web_mkt_desc",
            "VARCHAR"
        ],
        [
            "web_market_manager",
            "VARCHAR"
        ],
        [
            "web_company_id",
            "INT"
        ],
        [
            "web_company_name",
            "CHAR"
        ],
        [
            "web_street_number",
            "CHAR"
        ],
        [
            "web_street_name",
            "VARCHAR"
        ],
        [
            "web_street_type",
            "CHAR"
        ],
        [
            "web_suite_number",
            "CHAR"
        ],
        [
            "web_city",
            "VARCHAR"
        ],
        [
            "web_county",
            "VARCHAR"
        ],
        [
            "web_state",
            "CHAR"
        ],
        [
            "web_zip",
            "CHAR"
        ],
        [
            "web_country",
            "VARCHAR"
        ],
        [
            "web_gmt_offset",
            "DECIMAL"
        ],
        [
            "web_tax_percentage",
            "DECIMAL"
        ]
    ]
}